# Generated by Django 3.1.1 on 2020-09-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0002_bform_cform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BForm',
        ),
        migrations.DeleteModel(
            name='CForm',
        ),
    ]
