# Generated by Django 3.1.1 on 2020-09-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_planner', '0003_auto_20200907_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AForm',
            new_name='Lista',
        ),
    ]
