# Generated by Django 3.1.1 on 2020-09-15 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wedding_planner', '0004_auto_20200909_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
